name: Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run implemented tests
        run: |
          # Run only implemented tests
          if [ "$RUN_IMPLEMENTED_TESTS" == "true" ]; then
            npm test -- --tags=implemented
          fi

      - name: Run all tests (including unimplemented)
        run: npm test
